apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-deployment
  labels:
    app: azure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure
  template:
    metadata:
      labels:
        app: azure
    spec:
      containers:
      - name: azure
        image: docker.io/aadireddy/azure:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: MyApp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 30006
